# Generated by Django 5.2.9 on 2026-01-01 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Domain name (e.g., example.com)', max_length=255, unique=True)),
                ('title', models.CharField(help_text='Display name for this domain', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this domain/website')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this domain')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='domain-logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='domain-favicons/')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for this domain', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('contact_address', models.TextField(blank=True, help_text='Physical address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Domains',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='domains_dom_is_acti_88bf7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.CharField(blank=True, help_text='Default meta description for pages', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Default meta keywords (comma-separated)', max_length=255)),
                ('enable_contact_form', models.BooleanField(default=True)),
                ('enable_comments', models.BooleanField(default=False)),
                ('enable_search', models.BooleanField(default=True)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for this domain')),
                ('custom_js', models.TextField(blank=True, help_text='Custom JavaScript for this domain')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., UA-XXXXXXXXX-X or G-XXXXXXXXXX)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Domain Setting',
                'verbose_name_plural': 'Domain Settings',
            },
        ),
        migrations.CreateModel(
            name='DomainPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer (Read-only)'), ('editor', 'Editor (Can create/edit)'), ('admin', 'Admin (Full control)')], default='editor', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='domains.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Domain Permissions',
                'ordering': ['domain', 'user'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='domains_dom_user_id_c2d916_idx'), models.Index(fields=['domain', 'is_active'], name='domains_dom_domain__98d630_idx')],
                'unique_together': {('user', 'domain')},
            },
        ),
    ]
