# Generated by Django 5.2.9 on 2026-01-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainsetting',
            name='show_pages_link',
            field=models.BooleanField(default=True, help_text='Show the Pages link in the navigation bar'),
        ),
    ]
