# Generated by Django 5.2.9 on 2026-01-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domainsetting_show_pages_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainsetting',
            name='show_background_watermark',
            field=models.BooleanField(default=True, help_text='Show background watermark image on all pages'),
        ),
    ]
