# Generated by Django 5.2.9 on 2026-01-01 23:21

import cmsapp.media.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '__first__'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='domain',
            field=models.ForeignKey(default=cmsapp.media.models.get_default_domain, help_text='Domain this media belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='domain',
            field=models.ForeignKey(default=cmsapp.media.models.get_default_domain, help_text='Domain this folder belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to='domains.domain'),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='mediafolder',
            unique_together={('domain', 'slug', 'parent')},
        ),
        migrations.AddIndex(
            model_name='mediafolder',
            index=models.Index(fields=['domain', 'parent'], name='media_media_domain__697702_idx'),
        ),
    ]
