# Generated by Django 5.2.9 on 2026-01-05 20:57

import cmsapp.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediafile_domain_mediafolder_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=cmsapp.media.models.get_domain_media_path),
        ),
    ]
