# Generated by Django 5.2.9 on 2025-12-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('layout_type', models.CharField(choices=[('single-column', 'Single Column'), ('two-column', 'Two Column'), ('three-column', 'Three Column'), ('hero', 'Hero Layout'), ('masonry', 'Masonry Layout'), ('custom', 'Custom Layout')], default='single-column', max_length=20)),
                ('template_file', models.FileField(help_text='Django template file with .html extension', upload_to='templates/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Page Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stylesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('css_file', models.FileField(help_text='CSS file', upload_to='stylesheets/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stylesheets',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LayoutComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('header', 'Header'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('section', 'Section'), ('widget', 'Widget')], max_length=20)),
                ('html_content', models.TextField(help_text='HTML markup for the component')),
                ('css_class', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='templates.pagetemplate')),
            ],
            options={
                'verbose_name_plural': 'Layout Components',
                'unique_together': {('template', 'component_type')},
            },
        ),
    ]
