# Generated by Django 5.2.9 on 2026-01-01 23:21

import cmsapp.templates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '__first__'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetemplate',
            name='domain',
            field=models.ForeignKey(default=cmsapp.templates.models.get_default_domain, help_text='Domain this template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='page_templates', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='stylesheet',
            name='domain',
            field=models.ForeignKey(default=cmsapp.templates.models.get_default_domain, help_text='Domain this stylesheet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stylesheets', to='domains.domain'),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stylesheet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='pagetemplate',
            unique_together={('domain', 'name')},
        ),
        migrations.AddIndex(
            model_name='pagetemplate',
            index=models.Index(fields=['domain', 'is_active'], name='templates_p_domain__1ee42a_idx'),
        ),
    ]
