# Generated by Django 5.2.9 on 2026-01-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_pagetemplate_domain_stylesheet_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetemplate',
            name='template_name',
            field=models.CharField(blank=True, help_text='Path to template file (e.g., "modern/page_detail.html")', max_length=255),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='Django template file with .html extension', null=True, upload_to='templates/'),
        ),
    ]
