# Generated by Django 5.2.9 on 2026-01-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_pagetemplate_template_name_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE templates_pagetemplate DROP COLUMN IF EXISTS template_path;",
            reverse_sql="ALTER TABLE templates_pagetemplate ADD COLUMN template_path VARCHAR(255) DEFAULT '';",
        ),
    ]
