# Generated by Django 5.2.9 on 2026-01-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactinquiry',
            new_name='contact_con_created_1abdc3_idx',
            old_name='contact_con_created_idx',
        ),
        migrations.RenameIndex(
            model_name='contactinquiry',
            new_name='contact_con_status_267d02_idx',
            old_name='contact_con_status_idx',
        ),
    ]
