# Generated by ChatGPT
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contact_con_created_idx_contact_con_created_1abdc3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinquiry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='subject',
        ),
    ]
