# Generated by Django 5.2.9 on 2026-01-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contactinquiry_company_and_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('question', 'General Question'), ('service', 'Schedule Service'), ('feedback', 'Feedback'), ('other', 'Other')], default='question', max_length=20),
        ),
    ]
