# Generated by Django 5.2.9 on 2026-01-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_create_inquirytype_model'),
        ('domains', '0004_domainsetting_alert_toggles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquirytype',
            options={'ordering': ['order', 'label'], 'verbose_name_plural': 'Inquiry Types'},
        ),
        migrations.RemoveConstraint(
            model_name='inquirytype',
            name='unique_domain_inquiry_slug',
        ),
        migrations.RenameIndex(
            model_name='contactinquiry',
            new_name='contact_con_domain__907591_idx',
            old_name='contact_cont_domain_8f4d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='inquirytype',
            new_name='contact_inq_domain__99cd2e_idx',
            old_name='contact_inqu_domain_3f8a1c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='inquirytype',
            unique_together={('domain', 'slug')},
        ),
    ]
