# Generated by Django 5.2.9 on 2026-01-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_sync_inquiry_type_old_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinquiry',
            name='inquiry_type_old',
        ),
    ]
