# Generated by Django 5.2.9 on 2025-12-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
