# Generated by Django 5.2.9 on 2026-01-01 23:21

import cmsapp.pages.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '__first__'),
        ('pages', '0004_alter_page_content_alter_pageblock_content'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='domain',
            field=models.ForeignKey(default=cmsapp.pages.models.get_default_domain, help_text='Domain/website this page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='domains.domain'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('domain', 'slug')},
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['domain', '-created_at'], name='pages_page_domain__1118d6_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['domain', 'status'], name='pages_page_domain__03310f_idx'),
        ),
    ]
