# Generated by Django 5.2.9 on 2026-01-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_domain_alter_page_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
